Repository eclipse-edc/Technology-HuaweiCloud, pull requests merged in 2024-12, with the labels that each got.

#103 fix: Add missing permissions for CodeQl-Action #99
  .github/workflows/nightly.yaml
  .github/workflows/verify.yaml
Labels: bug

#106 build: fix compilation
  extensions/common/gaussdb/gaussdb-core/build.gradle.kts
  extensions/control-plane/store/asset-index-gaussdb/build.gradle.kts
  extensions/control-plane/store/contract-definition-store-gaussdb/build.gradle.kts
  extensions/control-plane/store/contract-negotiation-store-gaussdb/build.gradle.kts
  extensions/control-plane/store/contract-negotiation-store-gaussdb/src/test/java/com/huawei/cloud/store/gaussdb/contractnegotiationstore/GaussDbContractNegotiationStoreTest.java
  extensions/control-plane/store/data-plane-instance-store-gaussdb/build.gradle.kts
  extensions/control-plane/store/policy-definition-store-gaussdb/build.gradle.kts
  extensions/control-plane/store/policy-monitor-store-gaussdb/build.gradle.kts
  extensions/control-plane/store/policy-monitor-store-gaussdb/src/test/java/com/huawei/cloud/store/gaussdb/policymonitor/GaussDbPolicyMonitorProcessStoreTest.java
  extensions/control-plane/store/transfer-process-store-gaussdb/build.gradle.kts
  extensions/control-plane/store/transfer-process-store-gaussdb/src/test/java/com/huawei/cloud/store/gaussdb/transferprocess/GaussDbTransferProcessStoreTest.java
  gradle/libs.versions.toml
Labels: build

#108 fix: add write permission for prepare-workflow action #107
  .github/workflows/prepare-release.yml
Labels: bug

#109 fix: correct write permission for prepare-workflow action #107
  .github/workflows/prepare-release.yml
Labels: enhancement

#110 fix: add read permission for prepare-workflow action #107
  .github/workflows/prepare-release.yml
Labels: bug

#115 fix: Revert "chore(deps): bump edc from 0.11.0-SNAPSHOT to 0.11.0-20241210…
  gradle/libs.versions.toml
Labels: dependencies

#121 build: update shadow plugin group id
  e2e-tests/build.gradle.kts
  e2e-tests/src/test/java/com/huawei/cloud/tests/ObsTransferEndToEndTest.java
  gradle/libs.versions.toml
  launchers/e2e-test/build.gradle.kts
  launchers/huawei-cloud-runtime/build.gradle.kts
Labels: dependencies, build

#119 build: ignore edc upgrades
  .github/dependabot.yml
Labels: build
